# Improve colors
# set -ga terminal-overrides ",xterm-256color*:Tc"
set -ga terminal-overrides ",xterm-kitty*:Tc"
# set -g default-terminal "screen-256color"
setw -g mouse on
set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf
bind-key -r i run-shell "tmux neww tmux-cht.sh"

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @plugin 'dracula/tmux'
set -s default-terminal 'tmux-256color'


# plugins
# dracula customizations
set -g @dracula-plugins "battery cpu-usage ram-usage time"
# set -g @dracula-plugins "battery weather time"
set -g @dracula-show-powerline true
set -g @dracula-show-fahrenheit false
set -g @dracula-show-timezone false
set -g @dracula-military-time true

run '~/.tmux/plugins/tpm/tpm'
