local nnoremap = require("personal.keymap").nnoremap
local t = require('telescope.builtin')

nnoremap("<Leader>ff", function()
    t.find_files()
end)
nnoremap("<Leader>fg", function()
    t.git_files()
end)
nnoremap("<Leader>ft", function()
    t.live_grep()
end)
nnoremap("<Leader>fb", function()
    t.buffers()
end)
nnoremap("<Leader>fh", function()
    t.help_tags()
end)
nnoremap("<Leader>fsw", function()
  t.grep_string()
end)
nnoremap("<Leader>vrr", function()
    t.lsp_references()
end)
nnoremap("<Leader>fd", function()
    t.diagnostics({bufnr=0})
end)
nnoremap("<Leader>fwd", function()
    t.diagnostics()
end)
nnoremap("<Leader>s", function()
    t.lsp_document_symbols()
end)
nnoremap("<Leader>fk", function()
    t.keymaps()
end)
nnoremap("q:", function()
    t.command_history()
end)
nnoremap("q/", function()
    t.search_history()
end)
nnoremap("<Leader>fp", function()
    t.resume()
end)
